version: '3.1'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'hospitaldb' #your_db_name
      MYSQL_USER: 'admin' #your_username
      MYSQL_PASSWORD: 'password' #your_password
      MYSQL_ROOT_PASSWORD: 'password' #your_root_password
    ports:
      - '3306:3306' #default port for MySQL
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 manage.py migrate --no-input && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000' #default port for your django application
    depends_on:
      - db

volumes:
  mysql_data: